### ISSUE TITLE
The etag value changes in different elbs for same payload

### ISSUE THREAD

**Issue by kp198** [fastify/fastify-etag#107]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

The etag returned seems to change continuously for each elb ip and even for the same elb
Eg. etag was W/"etag" once, next time I make a request and for the same payload, the etag is changing to W/"newetag"

This happens consistently when I have multiple pods with multiple containers and doesn't happen when there is a single pod with single container. Interestingly for single pod setup the etag is not weak whereas for multiple pod setup it is weak.
Could this be a issue with crypto or something else?

I am using sha-256 now

**Comment by mcollina** [comment]
Thanks for reporting!

Can you provide steps to reproduce? We often need a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.

**Comment by kp198** [comment]
I'm unable to reproduce this but could you clarify if this is expected behaviour or not?
Also why is my hash always weak in the multiple pods setup?
Observed that this is not the case for single pod setup. It doesn't have W"/ appended.

**Comment by Uzlopak** [comment]
etag-package also takes  the modified time into account. So if you dont have a shared network filesystem between the pods, but actually each pod has its own filesystem then it could result in different etags.

**Comment by kp198** [comment]
@Uzlopak can you explain more about this, from the index.js here I didn't see any place where the time was taken into account.
In my case, I am fetching the data from a database and storing it in memory , processing it and then providing it with etag to end user.

**Comment by kp198** [comment]
Just tried it out in local by updating the cache data every minute or so and yes the tag changes here any idea how this can be prevented?

**Comment by Uzlopak** [comment]
@kp198 

Did you solve the issue?
