### ISSUE TITLE
How does response header get set?

### ISSUE THREAD

**Issue by jsumners** [fastify/fastify-etag#2]
https://github.com/fastify/fastify-etag/blob/0396b9b6739809bcba16a99538afaa91db5d90ed/index.js#L20

How does this get set? The request headers usually are not copied over to the outgoing response.

**Comment by mcollina** [comment]
This is not a request header. This is to support an application that is going to set a an Etag on its own, in other terms reply.header(‘etag’, ‘“foobar”’). When that happens, this module will not generate a new one.

**Comment by jsumners** [comment]
This should probably be mentioned in the readme. Otherwise, it could be a surprise.
