### ISSUE TITLE
Provide conditional request on this plugin?

### ISSUE THREAD

**Issue by RafaelGSS** [fastify/fastify-etag#22]
## 🚀 Feature Proposal

When we deal with race condition on update resource `Conditional Requests` help us to not override the data. This is normally used with `ETag`. However, this plugin doesn't provide the `onRequest` hook or export some decorator to use on `preValidation` for conditional requests. I would like to implement it, but since it is a major change (or a big change) I would like to ask if there is the best place for it or another plugin is better?

[Here](https://sookocheff.com/post/api/optimistic-locking-in-a-rest-api/) has a good example of usage:

**Comment by mcollina** [comment]
I'd say go for it as long as the default behavior is the same.

**Comment by RafaelGSS** [comment]
I thought better and thought that another plugin would make sense (depending on `fastify-etag`). I created [fastify-conditional-requests](https://github.com/RafaelGSS/fastify-conditional-requests).
