### ISSUE TITLE
Use Murmor2 (32-bit) instead FNV-1a as default

### ISSUE THREAD

**Issue by StarpTech** [fastify/fastify-etag#3]
Hi,
there is great comparison of hashing algorithm on [stackexchange](https://softwareengineering.stackexchange.com/questions/49550/which-hashing-algorithm-is-best-for-uniqueness-and-speed/145633#145633). While `FNV-1a` has great properties `Murmor2` is still much faster but with same collisions and distribution properties. Faster means less cpu cycles therefore better for node.js.

Here we can find the js implementation:
https://github.com/garycourt/murmurhash-js/blob/master/murmurhash2_gc.js

Why is it faster?
> I realized why Murmur is faster than the others. MurmurHash2 operates on four bytes at a time. Most algorithms are byte by byte:

**Comment by mcollina** [comment]
Would you mind to add this? We need to extend that logic to compute hashes over Buffer as well.

**Comment by StarpTech** [comment]
Yes, I will give it a try. Any opinion to add it as default or as another option?

**Comment by mcollina** [comment]
I would pick as default if it comes up faster

**Comment by StarpTech** [comment]
The performance of murmor2 compared to fnv1a is almost equal.
