### ISSUE TITLE
Release a new version (to bump fastify-plugin version to v3)

### ISSUE THREAD

**Issue by joelmukuthu** [fastify/fastify-etag#30]
## 🚀 Feature Proposal

Please release a new version of fastify-etag, to bump fastify-plugin version to v3.

## Motivation

To remove the "fastify not found, proceeding anyway" log messages.

## Example

N/A

**Comment by salmanm** [comment]
Released [v1.1.0](https://github.com/fastify/fastify-etag/releases/tag/v1.1.0)

**Comment by L2jLiga** [comment]
Should not it be released as v2.0.0? 

I see some breaking changes like requiring [fastify v3](https://github.com/fastify/fastify-etag/pull/13/files#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346R42)

**Comment by salmanm** [comment]
Ah right, my bad. There wasn't any tag so didn't realize it was done after the v1 release. Fixing.

**Comment by salmanm** [comment]
Released v2.0.0

**Comment by salmanm** [comment]
@L2jLiga
Ok so the major bump wasn't needed after all. v1.1.0 was correct.

![image](https://user-images.githubusercontent.com/2510597/103901129-bf94c980-511e-11eb-9f0f-1d24065a27f0.png)

Fastify v3 was bumped before fastify-etag v1.0.0 and there seems to be no other breaking change after that.

**Comment by joelmukuthu** [comment]
I'd recommend leaving 2.0.0 published as it is and creating a GitHub release for it to note that there aren't any breaking changes in the version. Thanks @salmanm for the release! :tada:

**Comment by L2jLiga** [comment]
Ok, I'd also keep 2.0.0

> Fastify v3 was bumped before went for v1.0.0 on fastify-etag and there seems to be no other breaking change after that.

My bad, I relied on v1.1.0 release notes and didn't notice that v1.0.0 tag absent
