### ISSUE TITLE
Weak Etag Support

### ISSUE THREAD

**Issue by savearray2** [fastify/fastify-etag#31]
## 🚀 Feature Proposal

If possible, an option to support generating/sending weak etags (`W/"abc"`) instead of strong etags would be great. 

## Motivation

Certain reverse proxies (e.g. envoy when using the [gzip](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/compressor/v3/compressor.proto#envoy-v3-api-msg-extensions-filters-http-compressor-v3-compressor) http filter) strip strong etags while leaving weak etags when compression is performed proxy-side.

## Example

A proposed example:

```js
fastify.register(etag, {
	weak: true
})
```

**Comment by zekth** [comment]
That could be nice. Would you send a PR for this?

**Comment by savearray2** [comment]
@zekth 
I've submitted the pull request! Thank you very much :)

**Comment by savearray2** [comment]
Merged! Thanks everyone :)
